### ISSUE TITLE
shout username box

### ISSUE THREAD

**Issue by SimJoSt** [hostedinspace/bremen.chat#2]
Die username Eingabe-Box sollte mit einem Standardwert befüllt und wenn möglich ausgeblendet sein, da sie sonst nur für Verwirrung sorgt.

**Comment by mortzu** [comment]
Das geht nur mit Codeanpassung

**Comment by SimJoSt** [comment]
Gut, dann ein verständlicher Vorgabewert.
Vielleicht web.bremen.chat? Shout?

**Comment by mortzu** [comment]
Sie ist weg
